spring.application.name=AplicacaoRabbitMQ


spring.rabbitmq.host=192.168.15.66
spring.rabbitmq.port=5672
spring.rabbitmq.username=guest
spring.rabbitmq.password=guest

spring.datasource.url=jdbc:postgresql://localhost:5433/AplicacaoRabbitMQ
spring.datasource.username=postgres
spring.datasource.password=minhasenha123
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=false


spring.mail.host=smtp.gmail.com
spring.mail.port=587
spring.mail.username=phelipegithub@gmail.com
spring.mail.password=sua-senha-de-app
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true